services:
  swaggerui:
    networks:
      - caddy
      - default
    labels:
      caddy: ${SWAGGERUI_SERVER}
      caddy.reverse_proxy: "{{upstreams 8080}}"

  pgrst:
    networks:
      - caddy
      - default
    labels:
      caddy: ${PGRST_OPENAPI_SERVER_PROXY_URI}
      caddy.reverse_proxy: "{{upstreams 3000}}"

  tsdb:
    networks:
      - default
    # For now not reqired, maybe for TLS Caddy L4 TCP/UDP
    # see: https://github.com/mholt/caddy-l4
    # labels:
    #   caddy: ${TIMESCALEDB_SERVER}
    #   caddy.reverse_proxy: "{{upstreams 5432}}"

networks:
  # Add caddy as an external network.
  caddy:
    external: true
