version: '3.8'

services:
  tsdb:
    image: timescale/timescaledb:${TIMESCALEDB_VERSION}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TIMESCALEDB_TELEMETRY: ${TIMESCALEDB_TELEMETRY}
      TS_TUNE_MEMORY: ${TS_TUNE_MEMORY}
      TS_TUNE_NUM_CPUS: ${TS_TUNE_NUM_CPUS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  pgdata: {}
