services:
  tsdb:
    networks:
      - caddy
    labels:
      caddy: ${TIMESCALEDB_SERVER}
      caddy.reverse_proxy: "{{upstreams 5432}}"

networks:
  # Add caddy as an external network.
  caddy:
    external: true
